CREATE OR REPLACE TABLE
	"{dld_database}"."{dld_table}_staging"(
		"area_id" Integer,
		"zone_id" Nullable(Integer),
		"parcel_id" Nullable(Integer),
		"land_number" Nullable(Integer),
		"land_sub_number" Nullable(Integer),
		"land_type_id" Nullable(Integer),
		"master_project_id" Nullable(Integer), 
		"master_project_en" Nullable(Varchar(90)), 
		"master_project_ar" Nullable(Varchar(150)),
		"project_id" Nullable(Integer),
		"project_name_ar" Nullable(Varchar(252)), 
		"project_name_en" Nullable(Varchar(154)),
		"building_number" Nullable(Varchar(66)),
		"parent_property_id" Nullable(Integer),
		"property_id" Nullable(Integer),
		"property_sub_type_id" Nullable(Integer),
		"is_free_hold" Nullable(Bool), 
		"is_lease_hold" Nullable(Bool), 
		"is_registered" Nullable(Bool),
		"pre_registration_number" Nullable(Varchar(20)),
		"creation_date" Nullable(Date),
		"built_up_area" Nullable(Float),
		"common_area" Nullable(Float),
		"actual_common_area" Nullable(Integer),
		"actual_area" Nullable(Float),
		"bld_levels" Nullable(Integer),
		"floors" Nullable(Integer),
		"rooms_en" Nullable(Varchar(46)), 
		"car_parks" Nullable(Integer),
		"elevators" Nullable(Integer),
		"swimming_pools" Nullable(Integer),
		"offices" Nullable(Integer),
		"shops" Nullable(Integer),
		"flats" Nullable(Integer)
	) 
    ENGINE = MergeTree()
    PRIMARY KEY("area_id");